services:
  xiaozhi-esp32-server:
    image: ccr.ccs.tencentyun.com/xinnan/xiaozhi-esp32-server:latest
    container_name: xiaozhi-esp32-server
    restart: always
    #security_opt:
    #  - seccomp:unconfined
    ports:
      - "8000:8000" # ws服务端
      - "8002:8002" # 管理后台
    volumes:
      # 配置文件 记得创建文件夹
      - ./data:/opt/xiaozhi-esp32-server/data
      # 模型文件 //可以挂载本地下载好的模型
      #- ./models:/opt/xiaozhi-esp32-server/models
      # 临时文件 //可以看log和音频文件 记得创建文件夹
      #- ./tmp:/opt/xiaozhi-esp32-server/tmp
